# Generated by Django 2.1 on 2018-08-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabber', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commented_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commented_to',
            new_name='to',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='posted_by',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='file_upload',
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
